<?php

// autoload_classmap.php @generated by TYPO3

$typo3InstallDir = PATH_site;

return array(
    'BK2K\\BootstrapPackage\\' => array($typo3InstallDir . 'typo3conf/ext/bootstrap_package/Classes'),
    'Sdgs\\YoutubeDemo\\' => array($typo3InstallDir . 'typo3conf/ext/youtube_demo/Classes'),
);
